/* The Koka island's ABI projection (C3 gold).
 *
 * The wire-generated callee trampoline (callee.c) speaks plain int64_t
 * from the dictionary's std/i64 side. Koka's real ABI is `kk_integer_t`
 * plus a `kk_context_t*`, so this adapter owns the projection, exactly
 * as Factorial.hs owns the GHC one:
 *
 *   int64_t kk_island_factorial(int64_t)              <- what the trampoline calls
 *   kk_factorial_island_factorial(kk_integer_t, ctx)  <- what koka really exports
 *
 * Init contract: koka needs its runtime up (kk_main_start) and the
 * module's init chain run (kk_factorial__init, which pulls in every std
 * module it references -- statically guarded, idempotent) before any
 * island call, and kk_factorial__done before exit. The generated
 * haskell-callee trampoline carries the analogous hs_init note; this
 * comment documents the koka contract, honored by the host.
 *
 * Mirrors the spike-era finding: the island's real entry name comes
 * from the wire plan (opsCalleeExport), not from this file -- the
 * trampoline filled with the adapter entry then links against it here.
 */
#include <stdint.h>
#include <kklib.h>

/* Generated by `koka -c -l factorial.kk` (see run_koka.sh stage 2):
 * declares kk_factorial_island_factorial, kk_factorial__init,
 * kk_factorial__done. Included rather than re-declared so the adapter
 * cannot drift from the compiler's real ABI. */
#include "factorial.h"

/* One-time runtime + module init. Called by the host before the first
 * crossing; kk_factorial__init runs each std module's static guard in
 * dependency order, so a second call is a no-op. */
static int kk_rts_up = 0;
void kk_island_init(void)
{
  if (kk_rts_up) return;
  kk_rts_up = 1;
  kk_context_t* ctx = kk_main_start(0, NULL);
  kk_factorial__init(ctx);
}

void kk_island_done(void)
{
  kk_context_t* ctx = kk_get_context();
  kk_factorial__done(ctx);
}

int64_t kk_island_factorial(int64_t n)
{
  kk_context_t* ctx = kk_get_context();
  return kk_smallint_from_integer(kk_factorial_island_factorial(kk_integer_from_int64(n, ctx), ctx));
}

extern void kk_std_core__done(kk_context_t* ctx); /* pulled by kk_factorial__done */
